// Database types for the Retexia Supabase schema.
// Generated by scripts/gen-types.mjs from supabase/migrations. Do not edit by hand:
//   pnpm db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      action_runs: {
        Row: {
          action_id: string | null
          action_key: string | null
          action_label: string | null
          created_at: string
          error: string | null
          finished_at: string | null
          id: string
          order_id: string
          request: Json | null
          response: Json | null
          started_at: string | null
          status: string
          triggered_by: string | null
          updated_at: string
        }
        Insert: {
          action_id?: string | null
          action_key?: string | null
          action_label?: string | null
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          order_id: string
          request?: Json | null
          response?: Json | null
          started_at?: string | null
          status?: string
          triggered_by?: string | null
          updated_at?: string
        }
        Update: {
          action_id?: string | null
          action_key?: string | null
          action_label?: string | null
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          order_id?: string
          request?: Json | null
          response?: Json | null
          started_at?: string | null
          status?: string
          triggered_by?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "action_runs_action_id_fkey"
            columns: ["action_id"]
            isOneToOne: false
            referencedRelation: "product_actions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "action_runs_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_saved_views: {
        Row: {
          created_at: string
          filters: Json
          id: string
          name: string
          page: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          filters?: Json
          id?: string
          name: string
          page: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          created_at?: string
          filters?: Json
          id?: string
          name?: string
          page?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      audit_logs: {
        Row: {
          action: string
          actor_email: string | null
          actor_id: string | null
          actor_role: string | null
          after: Json | null
          before: Json | null
          created_at: string
          id: string
          ip: string | null
          record_id: string | null
          summary: string | null
          table_name: string | null
          user_agent: string | null
        }
        Insert: {
          action: string
          actor_email?: string | null
          actor_id?: string | null
          actor_role?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          id?: string
          ip?: string | null
          record_id?: string | null
          summary?: string | null
          table_name?: string | null
          user_agent?: string | null
        }
        Update: {
          action?: string
          actor_email?: string | null
          actor_id?: string | null
          actor_role?: string | null
          after?: Json | null
          before?: Json | null
          created_at?: string
          id?: string
          ip?: string | null
          record_id?: string | null
          summary?: string | null
          table_name?: string | null
          user_agent?: string | null
        }
        Relationships: []
      }
      contact_messages: {
        Row: {
          business_name: string | null
          created_at: string
          email: string
          id: string
          message: string
          name: string
          phone: string | null
          product_id: string | null
          source_path: string | null
          status: string
          subject: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          business_name?: string | null
          created_at?: string
          email: string
          id?: string
          message: string
          name: string
          phone?: string | null
          product_id?: string | null
          source_path?: string | null
          status?: string
          subject?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          business_name?: string | null
          created_at?: string
          email?: string
          id?: string
          message?: string
          name?: string
          phone?: string | null
          product_id?: string | null
          source_path?: string | null
          status?: string
          subject?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "contact_messages_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      customer_notes: {
        Row: {
          author_id: string | null
          body: string
          created_at: string
          id: string
          pinned: boolean
          updated_at: string
          user_id: string
        }
        Insert: {
          author_id?: string | null
          body: string
          created_at?: string
          id?: string
          pinned?: boolean
          updated_at?: string
          user_id: string
        }
        Update: {
          author_id?: string | null
          body?: string
          created_at?: string
          id?: string
          pinned?: boolean
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      faqs: {
        Row: {
          answer: string
          created_at: string
          id: string
          is_visible: boolean
          product_id: string | null
          question: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          answer: string
          created_at?: string
          id?: string
          is_visible?: boolean
          product_id?: string | null
          question: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          answer?: string
          created_at?: string
          id?: string
          is_visible?: boolean
          product_id?: string | null
          question?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "faqs_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      form_fields: {
        Row: {
          created_at: string
          default_value: string | null
          form_id: string | null
          help_text: string | null
          id: string
          is_visible: boolean
          key: string
          label: string
          max: number | null
          min: number | null
          options: Json
          placeholder: string | null
          prefill_from: string | null
          required: boolean
          show_if: Json | null
          sort_order: number
          step_id: string
          type: string
          updated_at: string
          width: string
        }
        Insert: {
          created_at?: string
          default_value?: string | null
          form_id?: string | null
          help_text?: string | null
          id?: string
          is_visible?: boolean
          key: string
          label: string
          max?: number | null
          min?: number | null
          options?: Json
          placeholder?: string | null
          prefill_from?: string | null
          required?: boolean
          show_if?: Json | null
          sort_order?: number
          step_id: string
          type: string
          updated_at?: string
          width?: string
        }
        Update: {
          created_at?: string
          default_value?: string | null
          form_id?: string | null
          help_text?: string | null
          id?: string
          is_visible?: boolean
          key?: string
          label?: string
          max?: number | null
          min?: number | null
          options?: Json
          placeholder?: string | null
          prefill_from?: string | null
          required?: boolean
          show_if?: Json | null
          sort_order?: number
          step_id?: string
          type?: string
          updated_at?: string
          width?: string
        }
        Relationships: [
          {
            foreignKeyName: "form_fields_form_id_fkey"
            columns: ["form_id"]
            isOneToOne: false
            referencedRelation: "forms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "form_fields_step_id_fkey"
            columns: ["step_id"]
            isOneToOne: false
            referencedRelation: "form_steps"
            referencedColumns: ["id"]
          },
        ]
      }
      form_steps: {
        Row: {
          created_at: string
          description: string | null
          form_id: string
          id: string
          is_visible: boolean
          sort_order: number
          step_number: number
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          form_id: string
          id?: string
          is_visible?: boolean
          sort_order?: number
          step_number?: number
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          form_id?: string
          id?: string
          is_visible?: boolean
          sort_order?: number
          step_number?: number
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "form_steps_form_id_fkey"
            columns: ["form_id"]
            isOneToOne: false
            referencedRelation: "forms"
            referencedColumns: ["id"]
          },
        ]
      }
      forms: {
        Row: {
          created_at: string
          description: string | null
          id: string
          product_id: string | null
          slug: string
          submit_label: string | null
          success_message: string | null
          success_title: string | null
          title: string
          updated_at: string
          version: number
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          product_id?: string | null
          slug: string
          submit_label?: string | null
          success_message?: string | null
          success_title?: string | null
          title: string
          updated_at?: string
          version?: number
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          product_id?: string | null
          slug?: string
          submit_label?: string | null
          success_message?: string | null
          success_title?: string | null
          title?: string
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "forms_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      media: {
        Row: {
          alt: string | null
          created_at: string
          height: number | null
          id: string
          mime: string | null
          path: string
          size: number | null
          updated_at: string
          uploaded_by: string | null
          url: string
          width: number | null
        }
        Insert: {
          alt?: string | null
          created_at?: string
          height?: number | null
          id?: string
          mime?: string | null
          path: string
          size?: number | null
          updated_at?: string
          uploaded_by?: string | null
          url: string
          width?: number | null
        }
        Update: {
          alt?: string | null
          created_at?: string
          height?: number | null
          id?: string
          mime?: string | null
          path?: string
          size?: number | null
          updated_at?: string
          uploaded_by?: string | null
          url?: string
          width?: number | null
        }
        Relationships: []
      }
      navigation_items: {
        Row: {
          created_at: string
          href: string | null
          id: string
          is_visible: boolean
          kind: string
          label: string
          location: string
          open_in_new_tab: boolean
          signed_in_href: string | null
          signed_in_label: string | null
          sort_order: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          href?: string | null
          id?: string
          is_visible?: boolean
          kind?: string
          label: string
          location: string
          open_in_new_tab?: boolean
          signed_in_href?: string | null
          signed_in_label?: string | null
          sort_order?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          href?: string | null
          id?: string
          is_visible?: boolean
          kind?: string
          label?: string
          location?: string
          open_in_new_tab?: boolean
          signed_in_href?: string | null
          signed_in_label?: string | null
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      notifications_outbox: {
        Row: {
          attempts: number
          body: string | null
          channel: string
          created_at: string
          error: string | null
          event: string
          id: string
          order_id: string | null
          payload: Json
          recipient: string | null
          sent_at: string | null
          status: string
          subject: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          attempts?: number
          body?: string | null
          channel?: string
          created_at?: string
          error?: string | null
          event: string
          id?: string
          order_id?: string | null
          payload?: Json
          recipient?: string | null
          sent_at?: string | null
          status?: string
          subject?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          attempts?: number
          body?: string | null
          channel?: string
          created_at?: string
          error?: string | null
          event?: string
          id?: string
          order_id?: string | null
          payload?: Json
          recipient?: string | null
          sent_at?: string | null
          status?: string
          subject?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_outbox_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_counters: {
        Row: {
          last_value: number
          product_id: string
          year: number
        }
        Insert: {
          last_value?: number
          product_id: string
          year: number
        }
        Update: {
          last_value?: number
          product_id?: string
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_counters_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      order_events: {
        Row: {
          created_at: string
          created_by: string | null
          from_status: string | null
          id: string
          note: string | null
          order_id: string
          to_status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          from_status?: string | null
          id?: string
          note?: string | null
          order_id: string
          to_status: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          from_status?: string | null
          id?: string
          note?: string | null
          order_id?: string
          to_status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_notes: {
        Row: {
          author_id: string | null
          body: string
          created_at: string
          id: string
          order_id: string
          pinned: boolean
          updated_at: string
        }
        Insert: {
          author_id?: string | null
          body: string
          created_at?: string
          id?: string
          order_id: string
          pinned?: boolean
          updated_at?: string
        }
        Update: {
          author_id?: string | null
          body?: string
          created_at?: string
          id?: string
          order_id?: string
          pinned?: boolean
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_notes_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      order_status_transitions: {
        Row: {
          action_label: string
          created_at: string
          customer_note_template: string | null
          from_status: string
          id: string
          min_roles: string[]
          notify_customer_default: boolean
          requires_confirmed_payment: boolean
          requires_reason: boolean
          sort_order: number
          to_status: string
          updated_at: string
        }
        Insert: {
          action_label: string
          created_at?: string
          customer_note_template?: string | null
          from_status: string
          id?: string
          min_roles?: string[]
          notify_customer_default?: boolean
          requires_confirmed_payment?: boolean
          requires_reason?: boolean
          sort_order?: number
          to_status: string
          updated_at?: string
        }
        Update: {
          action_label?: string
          created_at?: string
          customer_note_template?: string | null
          from_status?: string
          id?: string
          min_roles?: string[]
          notify_customer_default?: boolean
          requires_confirmed_payment?: boolean
          requires_reason?: boolean
          sort_order?: number
          to_status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "order_status_transitions_from_status_fkey"
            columns: ["from_status"]
            isOneToOne: false
            referencedRelation: "order_statuses"
            referencedColumns: ["key"]
          },
          {
            foreignKeyName: "order_status_transitions_to_status_fkey"
            columns: ["to_status"]
            isOneToOne: false
            referencedRelation: "order_statuses"
            referencedColumns: ["key"]
          },
        ]
      }
      order_statuses: {
        Row: {
          created_at: string
          customer_can_cancel: boolean
          description: string | null
          is_final: boolean
          is_visible: boolean
          key: string
          label: string
          sort_order: number
          tone: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          customer_can_cancel?: boolean
          description?: string | null
          is_final?: boolean
          is_visible?: boolean
          key: string
          label: string
          sort_order?: number
          tone?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          customer_can_cancel?: boolean
          description?: string | null
          is_final?: boolean
          is_visible?: boolean
          key?: string
          label?: string
          sort_order?: number
          tone?: string
          updated_at?: string
        }
        Relationships: []
      }
      orders: {
        Row: {
          admin_note: string | null
          answers: Json
          assigned_to: string | null
          billing_cycle: string
          cancel_reason: string | null
          cancelled_at: string | null
          created_at: string
          currency: string | null
          customer_note: string | null
          form_id: string | null
          form_version: number | null
          id: string
          package_id: string
          package_name: string | null
          paddle_customer_id: string | null
          paddle_subscription_id: string | null
          paddle_transaction_id: string | null
          paused_at: string | null
          payhere_subscription_id: string | null
          price_amount: number | null
          price_override_reason: string | null
          product_id: string
          ref: string | null
          renews_at: string | null
          service_data: Json
          setup_fee: number | null
          source: string
          starts_at: string | null
          status: string
          status_note: string | null
          updated_at: string
          user_id: string | null
        }
        Insert: {
          admin_note?: string | null
          answers?: Json
          assigned_to?: string | null
          billing_cycle?: string
          cancel_reason?: string | null
          cancelled_at?: string | null
          created_at?: string
          currency?: string | null
          customer_note?: string | null
          form_id?: string | null
          form_version?: number | null
          id?: string
          package_id: string
          package_name?: string | null
          paddle_customer_id?: string | null
          paddle_subscription_id?: string | null
          paddle_transaction_id?: string | null
          paused_at?: string | null
          payhere_subscription_id?: string | null
          price_amount?: number | null
          price_override_reason?: string | null
          product_id: string
          ref?: string | null
          renews_at?: string | null
          service_data?: Json
          setup_fee?: number | null
          source?: string
          starts_at?: string | null
          status?: string
          status_note?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          admin_note?: string | null
          answers?: Json
          assigned_to?: string | null
          billing_cycle?: string
          cancel_reason?: string | null
          cancelled_at?: string | null
          created_at?: string
          currency?: string | null
          customer_note?: string | null
          form_id?: string | null
          form_version?: number | null
          id?: string
          package_id?: string
          package_name?: string | null
          paddle_customer_id?: string | null
          paddle_subscription_id?: string | null
          paddle_transaction_id?: string | null
          paused_at?: string | null
          payhere_subscription_id?: string | null
          price_amount?: number | null
          price_override_reason?: string | null
          product_id?: string
          ref?: string | null
          renews_at?: string | null
          service_data?: Json
          setup_fee?: number | null
          source?: string
          starts_at?: string | null
          status?: string
          status_note?: string | null
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orders_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_form_id_fkey"
            columns: ["form_id"]
            isOneToOne: false
            referencedRelation: "forms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "packages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_status_fkey"
            columns: ["status"]
            isOneToOne: false
            referencedRelation: "order_statuses"
            referencedColumns: ["key"]
          },
        ]
      }
      package_features: {
        Row: {
          created_at: string
          id: string
          included: boolean
          is_visible: boolean
          label: string
          package_id: string
          sort_order: number
          tooltip: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          included?: boolean
          is_visible?: boolean
          label: string
          package_id: string
          sort_order?: number
          tooltip?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          included?: boolean
          is_visible?: boolean
          label?: string
          package_id?: string
          sort_order?: number
          tooltip?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "package_features_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "packages"
            referencedColumns: ["id"]
          },
        ]
      }
      packages: {
        Row: {
          badge: string | null
          created_at: string
          cta_label: string | null
          currency: string | null
          description: string | null
          fine_print: string | null
          id: string
          is_active: boolean
          is_featured: boolean
          is_visible: boolean
          name: string
          paddle_price_monthly: string | null
          paddle_price_setup: string | null
          paddle_price_yearly: string | null
          price_monthly: number
          price_note: string | null
          price_yearly: number | null
          product_id: string
          setup_fee: number
          slug: string
          sort_order: number
          tagline: string | null
          updated_at: string
        }
        Insert: {
          badge?: string | null
          created_at?: string
          cta_label?: string | null
          currency?: string | null
          description?: string | null
          fine_print?: string | null
          id?: string
          is_active?: boolean
          is_featured?: boolean
          is_visible?: boolean
          name: string
          paddle_price_monthly?: string | null
          paddle_price_setup?: string | null
          paddle_price_yearly?: string | null
          price_monthly?: number
          price_note?: string | null
          price_yearly?: number | null
          product_id: string
          setup_fee?: number
          slug: string
          sort_order?: number
          tagline?: string | null
          updated_at?: string
        }
        Update: {
          badge?: string | null
          created_at?: string
          cta_label?: string | null
          currency?: string | null
          description?: string | null
          fine_print?: string | null
          id?: string
          is_active?: boolean
          is_featured?: boolean
          is_visible?: boolean
          name?: string
          paddle_price_monthly?: string | null
          paddle_price_setup?: string | null
          paddle_price_yearly?: string | null
          price_monthly?: number
          price_note?: string | null
          price_yearly?: number | null
          product_id?: string
          setup_fee?: number
          slug?: string
          sort_order?: number
          tagline?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "packages_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      paddle_events: {
        Row: {
          error: string | null
          event_type: string
          id: string
          occurred_at: string | null
          order_id: string | null
          payload: Json
          processed_at: string | null
          received_at: string
        }
        Insert: {
          error?: string | null
          event_type: string
          id: string
          occurred_at?: string | null
          order_id?: string | null
          payload?: Json
          processed_at?: string | null
          received_at?: string
        }
        Update: {
          error?: string | null
          event_type?: string
          id?: string
          occurred_at?: string | null
          order_id?: string | null
          payload?: Json
          processed_at?: string | null
          received_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "paddle_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      page_sections: {
        Row: {
          anchor: string | null
          background: string
          content: Json
          created_at: string
          eyebrow: string | null
          highlight: string | null
          id: string
          is_visible: boolean
          page_id: string
          sort_order: number
          subtitle: string | null
          title: string | null
          type: string
          updated_at: string
        }
        Insert: {
          anchor?: string | null
          background?: string
          content?: Json
          created_at?: string
          eyebrow?: string | null
          highlight?: string | null
          id?: string
          is_visible?: boolean
          page_id: string
          sort_order?: number
          subtitle?: string | null
          title?: string | null
          type: string
          updated_at?: string
        }
        Update: {
          anchor?: string | null
          background?: string
          content?: Json
          created_at?: string
          eyebrow?: string | null
          highlight?: string | null
          id?: string
          is_visible?: boolean
          page_id?: string
          sort_order?: number
          subtitle?: string | null
          title?: string | null
          type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "page_sections_page_id_fkey"
            columns: ["page_id"]
            isOneToOne: false
            referencedRelation: "pages"
            referencedColumns: ["id"]
          },
        ]
      }
      pages: {
        Row: {
          created_at: string
          id: string
          is_published: boolean
          og_image_url: string | null
          product_id: string | null
          seo_description: string | null
          seo_title: string | null
          show_in_sitemap: boolean
          slug: string
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_published?: boolean
          og_image_url?: string | null
          product_id?: string | null
          seo_description?: string | null
          seo_title?: string | null
          show_in_sitemap?: boolean
          slug: string
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_published?: boolean
          og_image_url?: string | null
          product_id?: string | null
          seo_description?: string | null
          seo_title?: string | null
          show_in_sitemap?: boolean
          slug?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "pages_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      payhere_events: {
        Row: {
          error: string | null
          id: string
          message: string
          order_id: string | null
          payload: Json
          processed_at: string | null
          received_at: string
        }
        Insert: {
          error?: string | null
          id: string
          message: string
          order_id?: string | null
          payload?: Json
          processed_at?: string | null
          received_at?: string
        }
        Update: {
          error?: string | null
          id?: string
          message?: string
          order_id?: string | null
          payload?: Json
          processed_at?: string | null
          received_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payhere_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount: number
          confirmed_at: string | null
          created_at: string
          currency: string | null
          id: string
          kind: string
          method: string
          note: string | null
          order_id: string
          paid_at: string | null
          period_end: string | null
          period_start: string | null
          proof_path: string | null
          receipt_number: string | null
          recorded_by: string | null
          reference: string | null
          status: string
          updated_at: string
          user_id: string | null
        }
        Insert: {
          amount: number
          confirmed_at?: string | null
          created_at?: string
          currency?: string | null
          id?: string
          kind?: string
          method?: string
          note?: string | null
          order_id: string
          paid_at?: string | null
          period_end?: string | null
          period_start?: string | null
          proof_path?: string | null
          receipt_number?: string | null
          recorded_by?: string | null
          reference?: string | null
          status?: string
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          amount?: number
          confirmed_at?: string | null
          created_at?: string
          currency?: string | null
          id?: string
          kind?: string
          method?: string
          note?: string | null
          order_id?: string
          paid_at?: string | null
          period_end?: string | null
          period_start?: string | null
          proof_path?: string | null
          receipt_number?: string | null
          recorded_by?: string | null
          reference?: string | null
          status?: string
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      product_actions: {
        Row: {
          allowed_statuses: string[]
          confirm_text: string | null
          created_at: string
          description: string | null
          id: string
          is_enabled: boolean
          key: string
          label: string
          min_roles: string[]
          on_success_note: string | null
          on_success_status: string | null
          payload_fields: string[]
          product_id: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          allowed_statuses?: string[]
          confirm_text?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_enabled?: boolean
          key: string
          label: string
          min_roles?: string[]
          on_success_note?: string | null
          on_success_status?: string | null
          payload_fields?: string[]
          product_id: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          allowed_statuses?: string[]
          confirm_text?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_enabled?: boolean
          key?: string
          label?: string
          min_roles?: string[]
          on_success_note?: string | null
          on_success_status?: string | null
          payload_fields?: string[]
          product_id?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_actions_on_success_status_fkey"
            columns: ["on_success_status"]
            isOneToOne: false
            referencedRelation: "order_statuses"
            referencedColumns: ["key"]
          },
          {
            foreignKeyName: "product_actions_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_features: {
        Row: {
          created_at: string
          description: string | null
          icon: string | null
          id: string
          is_visible: boolean
          product_id: string
          sort_order: number
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          is_visible?: boolean
          product_id: string
          sort_order?: number
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          is_visible?: boolean
          product_id?: string
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "product_features_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      product_service_fields: {
        Row: {
          created_at: string
          help_text: string | null
          id: string
          is_visible: boolean
          key: string
          label: string
          options: Json
          product_id: string
          required_for_status: string | null
          sort_order: number
          type: string
          updated_at: string
          visible_to_customer: boolean
        }
        Insert: {
          created_at?: string
          help_text?: string | null
          id?: string
          is_visible?: boolean
          key: string
          label: string
          options?: Json
          product_id: string
          required_for_status?: string | null
          sort_order?: number
          type?: string
          updated_at?: string
          visible_to_customer?: boolean
        }
        Update: {
          created_at?: string
          help_text?: string | null
          id?: string
          is_visible?: boolean
          key?: string
          label?: string
          options?: Json
          product_id?: string
          required_for_status?: string | null
          sort_order?: number
          type?: string
          updated_at?: string
          visible_to_customer?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "product_service_fields_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_service_fields_required_for_status_fkey"
            columns: ["required_for_status"]
            isOneToOne: false
            referencedRelation: "order_statuses"
            referencedColumns: ["key"]
          },
        ]
      }
      products: {
        Row: {
          auto_activate: boolean
          code: string
          color_dark: string
          color_light: string
          color_soft_dark: string
          color_soft_light: string
          created_at: string
          description: string | null
          icon: string | null
          id: string
          is_visible: boolean
          name: string
          onboarding_form_id: string | null
          paddle_product_id: string | null
          page_slug: string | null
          panel_live: boolean
          panel_url: string | null
          pay_online: boolean
          short_name: string
          slug: string
          sort_order: number
          status: string
          tagline: string | null
          updated_at: string
        }
        Insert: {
          auto_activate?: boolean
          code: string
          color_dark?: string
          color_light?: string
          color_soft_dark?: string
          color_soft_light?: string
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          is_visible?: boolean
          name: string
          onboarding_form_id?: string | null
          paddle_product_id?: string | null
          page_slug?: string | null
          panel_live?: boolean
          panel_url?: string | null
          pay_online?: boolean
          short_name: string
          slug: string
          sort_order?: number
          status?: string
          tagline?: string | null
          updated_at?: string
        }
        Update: {
          auto_activate?: boolean
          code?: string
          color_dark?: string
          color_light?: string
          color_soft_dark?: string
          color_soft_light?: string
          created_at?: string
          description?: string | null
          icon?: string | null
          id?: string
          is_visible?: boolean
          name?: string
          onboarding_form_id?: string | null
          paddle_product_id?: string | null
          page_slug?: string | null
          panel_live?: boolean
          panel_url?: string | null
          pay_online?: boolean
          short_name?: string
          slug?: string
          sort_order?: number
          status?: string
          tagline?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_onboarding_form_id_fkey"
            columns: ["onboarding_form_id"]
            isOneToOne: false
            referencedRelation: "forms"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          business_name: string | null
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          marketing_opt_in: boolean
          phone: string | null
          role: string
          updated_at: string
          whatsapp: string | null
        }
        Insert: {
          avatar_url?: string | null
          business_name?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          marketing_opt_in?: boolean
          phone?: string | null
          role?: string
          updated_at?: string
          whatsapp?: string | null
        }
        Update: {
          avatar_url?: string | null
          business_name?: string | null
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          marketing_opt_in?: boolean
          phone?: string | null
          role?: string
          updated_at?: string
          whatsapp?: string | null
        }
        Relationships: []
      }
      receipt_counters: {
        Row: {
          last_value: number
          prefix: string
          year: number
        }
        Insert: {
          last_value?: number
          prefix: string
          year: number
        }
        Update: {
          last_value?: number
          prefix?: string
          year?: number
        }
        Relationships: []
      }
      services: {
        Row: {
          created_at: string
          description: string | null
          href: string | null
          icon: string | null
          id: string
          is_visible: boolean
          sort_order: number
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          href?: string | null
          icon?: string | null
          id?: string
          is_visible?: boolean
          sort_order?: number
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          href?: string | null
          icon?: string | null
          id?: string
          is_visible?: boolean
          sort_order?: number
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      site_settings: {
        Row: {
          address: string | null
          announcement_enabled: boolean
          announcement_href: string | null
          announcement_text: string | null
          auth_google_enabled: boolean
          auth_magic_link_enabled: boolean
          business_hours: string | null
          contact_email: string | null
          contact_phone: string | null
          copyright_text: string | null
          created_at: string
          currency_code: string
          currency_locale: string
          default_theme: string
          favicon_url: string | null
          footer_text: string | null
          id: number
          invoice_address: string | null
          invoice_business_name: string | null
          invoice_footer: string | null
          invoice_logo_url: string | null
          logo_dark_url: string | null
          logo_url: string | null
          maintenance_message: string | null
          maintenance_mode: boolean
          og_image_url: string | null
          online_payments: boolean
          payment_instructions: string | null
          receipt_prefix: string
          seo_default_description: string | null
          seo_default_title: string | null
          seo_title_template: string
          site_name: string
          social_links: Json
          tagline: string | null
          theme: Json
          updated_at: string
          whatsapp_default_message: string | null
          whatsapp_number: string | null
        }
        Insert: {
          address?: string | null
          announcement_enabled?: boolean
          announcement_href?: string | null
          announcement_text?: string | null
          auth_google_enabled?: boolean
          auth_magic_link_enabled?: boolean
          business_hours?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          copyright_text?: string | null
          created_at?: string
          currency_code?: string
          currency_locale?: string
          default_theme?: string
          favicon_url?: string | null
          footer_text?: string | null
          id?: number
          invoice_address?: string | null
          invoice_business_name?: string | null
          invoice_footer?: string | null
          invoice_logo_url?: string | null
          logo_dark_url?: string | null
          logo_url?: string | null
          maintenance_message?: string | null
          maintenance_mode?: boolean
          og_image_url?: string | null
          online_payments?: boolean
          payment_instructions?: string | null
          receipt_prefix?: string
          seo_default_description?: string | null
          seo_default_title?: string | null
          seo_title_template?: string
          site_name?: string
          social_links?: Json
          tagline?: string | null
          theme?: Json
          updated_at?: string
          whatsapp_default_message?: string | null
          whatsapp_number?: string | null
        }
        Update: {
          address?: string | null
          announcement_enabled?: boolean
          announcement_href?: string | null
          announcement_text?: string | null
          auth_google_enabled?: boolean
          auth_magic_link_enabled?: boolean
          business_hours?: string | null
          contact_email?: string | null
          contact_phone?: string | null
          copyright_text?: string | null
          created_at?: string
          currency_code?: string
          currency_locale?: string
          default_theme?: string
          favicon_url?: string | null
          footer_text?: string | null
          id?: number
          invoice_address?: string | null
          invoice_business_name?: string | null
          invoice_footer?: string | null
          invoice_logo_url?: string | null
          logo_dark_url?: string | null
          logo_url?: string | null
          maintenance_message?: string | null
          maintenance_mode?: boolean
          og_image_url?: string | null
          online_payments?: boolean
          payment_instructions?: string | null
          receipt_prefix?: string
          seo_default_description?: string | null
          seo_default_title?: string | null
          seo_title_template?: string
          site_name?: string
          social_links?: Json
          tagline?: string | null
          theme?: Json
          updated_at?: string
          whatsapp_default_message?: string | null
          whatsapp_number?: string | null
        }
        Relationships: []
      }
      site_strings: {
        Row: {
          created_at: string
          description: string | null
          key: string
          updated_at: string
          value: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          key: string
          updated_at?: string
          value: string
        }
        Update: {
          created_at?: string
          description?: string | null
          key?: string
          updated_at?: string
          value?: string
        }
        Relationships: []
      }
      staff_settings: {
        Row: {
          created_at: string
          id: number
          notification_settings: Json
          staff_notification_emails: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: number
          notification_settings?: Json
          staff_notification_emails?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: number
          notification_settings?: Json
          staff_notification_emails?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      testimonials: {
        Row: {
          author_name: string
          author_role: string | null
          avatar_url: string | null
          company: string | null
          created_at: string
          id: string
          is_visible: boolean
          product_id: string | null
          quote: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          author_name: string
          author_role?: string | null
          avatar_url?: string | null
          company?: string | null
          created_at?: string
          id?: string
          is_visible?: boolean
          product_id?: string | null
          quote: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          author_name?: string
          author_role?: string | null
          avatar_url?: string | null
          company?: string | null
          created_at?: string
          id?: string
          is_visible?: boolean
          product_id?: string | null
          quote?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "testimonials_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      waitlist: {
        Row: {
          created_at: string
          email: string
          id: string
          product_id: string
          updated_at: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          product_id: string
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          product_id?: string
          updated_at?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "waitlist_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      staff_customers: {
        Row: {
          active_products: string[] | null
          avatar_url: string | null
          banned_until: string | null
          business_name: string | null
          created_at: string | null
          email: string | null
          email_confirmed_at: string | null
          full_name: string | null
          id: string | null
          is_banned: boolean | null
          last_sign_in_at: string | null
          lifetime_paid: number | null
          marketing_opt_in: boolean | null
          mfa_enabled: boolean | null
          orders_count: number | null
          phone: string | null
          role: string | null
          search: string | null
          updated_at: string | null
          whatsapp: string | null
        }
        Relationships: []
      }
      staff_orders: {
        Row: {
          admin_note: string | null
          answers: Json | null
          assigned_to: string | null
          assignee_name: string | null
          billing_cycle: string | null
          cancel_reason: string | null
          cancelled_at: string | null
          created_at: string | null
          currency: string | null
          customer_business: string | null
          customer_email: string | null
          customer_name: string | null
          customer_note: string | null
          customer_phone: string | null
          customer_whatsapp: string | null
          form_id: string | null
          form_version: number | null
          id: string | null
          monthly_value: number | null
          package_id: string | null
          package_name: string | null
          paid_total: number | null
          paused_at: string | null
          pending_payments: number | null
          price_amount: number | null
          price_override_reason: string | null
          product_code: string | null
          product_id: string | null
          product_name: string | null
          product_short_name: string | null
          product_slug: string | null
          ref: string | null
          renews_at: string | null
          search: string | null
          service_data: Json | null
          setup_fee: number | null
          source: string | null
          starts_at: string | null
          status: string | null
          status_is_final: boolean | null
          status_label: string | null
          status_note: string | null
          status_tone: string | null
          updated_at: string | null
          user_id: string | null
        }
        Relationships: []
      }
      staff_payments: {
        Row: {
          amount: number | null
          billing_cycle: string | null
          confirmed_at: string | null
          created_at: string | null
          currency: string | null
          customer_business: string | null
          customer_email: string | null
          customer_name: string | null
          id: string | null
          kind: string | null
          method: string | null
          note: string | null
          order_id: string | null
          order_ref: string | null
          package_name: string | null
          paid_at: string | null
          period_end: string | null
          period_start: string | null
          product_id: string | null
          product_short_name: string | null
          product_slug: string | null
          proof_path: string | null
          receipt_number: string | null
          recorded_by: string | null
          recorded_by_name: string | null
          reference: string | null
          search: string | null
          signed_amount: number | null
          status: string | null
          updated_at: string | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      admin_action_secret_status: { Args: { p_product_id: string }; Returns: Json }
      admin_anonymise_user: { Args: { p_user_id: string }; Returns: undefined }
      admin_assign_order: { Args: { p_order_id: string; p_user_id: string }; Returns: undefined }
      admin_change_order_status: { Args: { p_order_id: string; p_to_status: string; p_customer_note?: string; p_internal_note?: string; p_notify?: boolean; p_override_reason?: string }; Returns: Json }
      admin_create_order: { Args: { p: Json }; Returns: Json }
      admin_create_product: { Args: { p: Json }; Returns: string }
      admin_dashboard: { Args: { p_product_id?: string; p_from?: string; p_to?: string }; Returns: Json }
      admin_duplicate_product: { Args: { p_product_id: string; p_new_slug: string; p_new_name: string; p_new_code?: string }; Returns: string }
      admin_form_locked_keys: { Args: { p_form_id: string }; Returns: string[] }
      admin_integration_status: { Args: never; Returns: Json }
      admin_order_secret_status: { Args: { p_order_id: string }; Returns: Json }
      admin_reorder: { Args: { p_table: string; p_ids: string[] }; Returns: undefined }
      admin_reveal_order_secret: { Args: { p_order_id: string; p_key: string }; Returns: string }
      admin_save_form: { Args: { p: Json }; Returns: number }
      admin_set_action_secret: { Args: { p_action_id: string; p_webhook_url?: string; p_signing_secret?: string }; Returns: undefined }
      admin_set_integration_settings: { Args: { p: Json }; Returns: undefined }
      admin_set_service_data: { Args: { p_order_id: string; p_values: Json }; Returns: Json }
      admin_start_action_run: { Args: { p_order_id: string; p_action_id: string }; Returns: Json }
      admin_update_order: { Args: { p_order_id: string; p_changes: Json; p_reason?: string }; Returns: Json }
      cancel_order: { Args: { p_order_id: string; p_reason?: string }; Returns: string }
      customer_cancelled_subscription: { Args: { p_order_id: string }; Returns: undefined }
      customer_order_service_fields: { Args: { p_order_id: string }; Returns: Json }
      customer_set_paddle_transaction: { Args: { p_order_id: string; p_transaction_id: string }; Returns: undefined }
      customer_submit_payment_proof: { Args: { p_order_id: string; p_proof_path: string; p_reference?: string; p_note?: string }; Returns: string }
      has_role: { Args: { roles: string[] }; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      is_privileged: { Args: never; Returns: boolean }
      is_staff: { Args: never; Returns: boolean }
      request_role: { Args: never; Returns: string }
      staff_role: { Args: never; Returns: string }
      svc_apply_action_result: { Args: { p_run_id: string; p_status: string; p_service_data?: Json; p_order_status?: string; p_customer_note?: string; p_error?: string; p_response?: Json }; Returns: Json }
      svc_get_action_secret: { Args: { p_action_id: string }; Returns: Json }
      svc_get_integration_settings: { Args: never; Returns: Json }
      svc_get_order_secrets: { Args: { p_order_id: string; p_keys: string[] }; Returns: Json }
      svc_paddle_payment: { Args: { p: Json }; Returns: Json }
      svc_paddle_refund: { Args: { p: Json }; Returns: Json }
      svc_paddle_subscription: { Args: { p: Json }; Returns: Json }
      svc_payhere_payment: { Args: { p: Json }; Returns: Json }
      svc_payhere_subscription: { Args: { p: Json }; Returns: Json }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
