-- =====================================================================
-- 0006: Retexia Lingo (WhatsApp bot) inside the main Retexia project, in
-- its own schema. Same tables as the original Lingo project, plus:
--   * lingo_users.owner_id: the customer's Retexia login (links the panel);
--   * Row Level Security: owners see their own data, the Retexia team reads all;
--   * the Evolution API key is never readable by customers;
--   * panel stats functions and the public "lingo-products" photo bucket.
-- Safe to run again. After running: Settings → API → Exposed schemas → add "lingo".
-- =====================================================================

create schema if not exists lingo;
grant usage on schema lingo to anon, authenticated, service_role;

create table if not exists lingo.lingo_users (
  id                 bigint generated by default as identity primary key,
  owner_id           uuid references auth.users (id) on delete set null,
  business_name      text not null,
  evolution_instance text not null unique,
  evolution_base_url text not null,
  evolution_apikey   text not null,
  owner_phone        text,
  staff_name         text,
  default_language   text not null default 'singlish' check (default_language in ('si', 'singlish', 'en', 'ta')),
  content_language   text not null default 'singlish' check (content_language in ('si', 'singlish', 'en', 'ta')),
  followup_hours     integer not null default 5,
  delivery_days      integer not null default 3,
  active             boolean not null default true,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
alter table lingo.lingo_users add column if not exists owner_id uuid references auth.users (id) on delete set null;
create index if not exists lingo_users_owner_idx on lingo.lingo_users (owner_id);

create table if not exists lingo.business_details (
  id                   bigint generated by default as identity primary key,
  lingo_user_id        bigint not null unique references lingo.lingo_users (id) on delete cascade,
  business_type        text,
  about                text,
  address              text,
  location_url         text,
  opening_hours        text,
  contact_phone        text,
  website              text,
  delivery_areas       text,
  delivery_time        text,
  default_delivery_fee numeric not null default 0,
  payment_methods      text,
  extra_info           text,
  updated_at           timestamptz not null default now()
);

create table if not exists lingo.products (
  id                bigint generated by default as identity primary key,
  lingo_user_id     bigint references lingo.lingo_users (id) on delete cascade,
  product_name      text not null,
  short_description text,
  long_description  text,
  price             numeric not null default 0,
  delivery_fee      numeric,
  ingredients       text,
  application       text,
  precautions       text,
  symptoms          text,
  aliases           text,
  word_description  text,
  picture_url       text,
  product_id_feeder integer,
  active            boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists products_user_idx on lingo.products (lingo_user_id);

create table if not exists lingo.customers (
  id                   bigint generated by default as identity primary key,
  lingo_user_id        bigint not null references lingo.lingo_users (id) on delete cascade,
  remote_jid           text not null,
  number               text,
  whatsapp_name        text,
  customer_name        text,
  address              text,
  delivery_phone       text,
  language             text check (language in ('si', 'singlish', 'en', 'ta')),
  selected_product     bigint references lingo.products (id) on delete set null,
  seen_products        bigint[] not null default '{}',
  bot_paused           boolean not null default false,
  last_customer_msg_at timestamptz,
  last_bot_msg_at      timestamptz,
  followup_due         boolean not null default false,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (lingo_user_id, remote_jid)
);
create index if not exists customers_user_last_idx on lingo.customers (lingo_user_id, last_customer_msg_at desc);

create table if not exists lingo.orders (
  id                bigint generated by default as identity primary key,
  lingo_user_id     bigint not null references lingo.lingo_users (id) on delete cascade,
  customer_id       bigint not null references lingo.customers (id) on delete cascade,
  product_id        bigint references lingo.products (id) on delete set null,
  product_name      text,
  quantity          integer not null default 1 check (quantity > 0),
  unit_price        numeric not null default 0,
  delivery_fee      numeric not null default 0,
  total_price       numeric generated always as (quantity::numeric * unit_price + delivery_fee) stored,
  status            text not null default 'draft' check (status in ('draft', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')),
  customer_name     text,
  address           text,
  delivery_phone    text,
  cancel_reason     text,
  status_changed_at timestamptz not null default now(),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists orders_user_created_idx on lingo.orders (lingo_user_id, created_at desc);
create index if not exists orders_customer_idx on lingo.orders (customer_id, status);

create table if not exists lingo.messages (
  id            bigint generated by default as identity primary key,
  lingo_user_id bigint not null references lingo.lingo_users (id) on delete cascade,
  customer_id   bigint not null references lingo.customers (id) on delete cascade,
  role          text not null check (role in ('user', 'assistant', 'summary')),
  content       text not null,
  quoted_text   text,
  media_type    text,
  wa_message_id text,
  processed     boolean not null default false,
  created_at    timestamptz not null default now()
);
create index if not exists messages_user_created_idx on lingo.messages (lingo_user_id, created_at);
create index if not exists messages_customer_role_idx on lingo.messages (customer_id, role);

create table if not exists lingo.fixed_messages (
  id            bigint generated by default as identity primary key,
  lingo_user_id bigint references lingo.lingo_users (id) on delete cascade,
  key           text not null,
  language      text not null check (language in ('si', 'singlish', 'en', 'ta')),
  content       text not null,
  updated_at    timestamptz not null default now()
);
create index if not exists fixed_messages_lookup_idx on lingo.fixed_messages (key, language, lingo_user_id);

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
create or replace function lingo.owns(p_user bigint) returns boolean
language sql stable security definer set search_path = lingo, public as $$
  select exists (select 1 from lingo.lingo_users where id = p_user and owner_id = auth.uid());
$$;

do $$
declare t text;
begin
  foreach t in array array['lingo_users', 'business_details', 'products', 'customers', 'orders', 'messages', 'fixed_messages'] loop
    execute format('alter table lingo.%I enable row level security', t);
  end loop;
end $$;

drop policy if exists own_account on lingo.lingo_users;
create policy own_account on lingo.lingo_users for select to authenticated
  using (owner_id = (select auth.uid()) or (select public.is_privileged()));
drop policy if exists own_account_update on lingo.lingo_users;
create policy own_account_update on lingo.lingo_users for update to authenticated
  using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));

do $$
declare t text;
begin
  foreach t in array array['business_details', 'products', 'customers', 'orders'] loop
    execute format('drop policy if exists own_rows on lingo.%I', t);
    execute format('create policy own_rows on lingo.%I for all to authenticated using (lingo.owns(lingo_user_id) or (select public.is_privileged())) with check (lingo.owns(lingo_user_id))', t);
  end loop;
end $$;
-- Messages: no chat reading from the browser (the panel shows numbers only); staff may read.
drop policy if exists staff_read on lingo.messages;
create policy staff_read on lingo.messages for select to authenticated using ((select public.is_privileged()));
-- Fixed replies: the shared defaults (no owner) and your own versions.
drop policy if exists read_replies on lingo.fixed_messages;
create policy read_replies on lingo.fixed_messages for select to authenticated
  using (lingo_user_id is null or lingo.owns(lingo_user_id) or (select public.is_privileged()));
drop policy if exists own_replies on lingo.fixed_messages;
create policy own_replies on lingo.fixed_messages for all to authenticated
  using (lingo_user_id is not null and lingo.owns(lingo_user_id)) with check (lingo_user_id is not null and lingo.owns(lingo_user_id));

revoke all on all tables in schema lingo from anon, authenticated;
-- lingo_users: everything except the Evolution connection details.
grant select (id, owner_id, business_name, evolution_instance, owner_phone, staff_name, default_language, content_language,
              followup_hours, delivery_days, active, created_at, updated_at) on lingo.lingo_users to authenticated;
grant update (business_name, owner_phone, staff_name, default_language, content_language, followup_hours, delivery_days, active, updated_at)
  on lingo.lingo_users to authenticated;
grant select, insert, update on lingo.business_details, lingo.products, lingo.fixed_messages to authenticated;
grant delete on lingo.products, lingo.fixed_messages to authenticated;
grant select, update on lingo.customers, lingo.orders to authenticated;
grant select on lingo.messages to authenticated;
grant all on all tables in schema lingo to service_role;
grant usage, select on all sequences in schema lingo to service_role, authenticated;

-- ---------------------------------------------------------------------
-- Panel stats (server-side only)
-- ---------------------------------------------------------------------
create or replace function lingo.panel_customer_stats(p_user bigint)
returns table (customer_id bigint, user_messages bigint, bot_messages bigint, orders bigint, confirmed_orders bigint,
               spent numeric, last_order_status text, last_order_at timestamptz)
language sql stable set search_path = lingo, public as $$
  with m as (
    select customer_id, count(*) filter (where role = 'user') as u, count(*) filter (where role = 'assistant') as a
      from lingo.messages where lingo_user_id = p_user group by customer_id
  ), o as (
    select customer_id, count(*) as n,
           count(*) filter (where status in ('confirmed', 'processing', 'shipped', 'delivered')) as k,
           coalesce(sum(total_price) filter (where status in ('confirmed', 'processing', 'shipped', 'delivered')), 0) as s,
           (array_agg(status order by created_at desc))[1] as last_status,
           max(created_at) as last_at
      from lingo.orders where lingo_user_id = p_user group by customer_id
  )
  select c.id, coalesce(m.u, 0), coalesce(m.a, 0), coalesce(o.n, 0), coalesce(o.k, 0), coalesce(o.s, 0), o.last_status, o.last_at
    from lingo.customers c left join m on m.customer_id = c.id left join o on o.customer_id = c.id
   where c.lingo_user_id = p_user;
$$;

create or replace function lingo.panel_daily_stats(p_user bigint, p_days int default 30)
returns table (day date, customer_messages bigint, active_customers bigint, new_customers bigint, orders bigint, revenue numeric)
language sql stable set search_path = lingo, public as $$
  with d as (
    select generate_series((now() at time zone 'Asia/Colombo')::date - (p_days - 1), (now() at time zone 'Asia/Colombo')::date, interval '1 day')::date as day
  )
  select d.day,
    (select count(*) from lingo.messages m where m.lingo_user_id = p_user and m.role = 'user' and (m.created_at at time zone 'Asia/Colombo')::date = d.day),
    (select count(distinct m.customer_id) from lingo.messages m where m.lingo_user_id = p_user and m.role = 'user' and (m.created_at at time zone 'Asia/Colombo')::date = d.day),
    (select count(*) from lingo.customers c where c.lingo_user_id = p_user and (c.created_at at time zone 'Asia/Colombo')::date = d.day),
    (select count(*) from lingo.orders o where o.lingo_user_id = p_user and o.status <> 'draft' and (o.created_at at time zone 'Asia/Colombo')::date = d.day),
    (select coalesce(sum(o.total_price), 0) from lingo.orders o where o.lingo_user_id = p_user and o.status in ('confirmed', 'processing', 'shipped', 'delivered')
       and (o.created_at at time zone 'Asia/Colombo')::date = d.day)
  from d order by d.day;
$$;

revoke execute on all functions in schema lingo from public, anon;
grant execute on function lingo.owns(bigint) to authenticated;
revoke execute on function lingo.panel_customer_stats(bigint), lingo.panel_daily_stats(bigint, int) from authenticated;
grant execute on all functions in schema lingo to service_role;

-- ---------------------------------------------------------------------
-- Database role for the n8n Lingo workflow (unqualified names → lingo.*).
-- ---------------------------------------------------------------------
do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'lingo_n8n') then create role lingo_n8n nologin; end if;
end $$;
alter role lingo_n8n set search_path = lingo, public;
grant usage on schema lingo, public to lingo_n8n;
grant select, insert, update, delete on all tables in schema lingo to lingo_n8n;
grant usage, select on all sequences in schema lingo to lingo_n8n;
alter default privileges in schema lingo grant select, insert, update, delete on tables to lingo_n8n;

-- Product photos the bot sends on WhatsApp need a public URL.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('lingo-products', 'lingo-products', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
